apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: spring-app
    namespace: argocd
spec:
    destination:
        namespace: default
        server: https://kubernetes.default.svc
    project: default
    source:
        repoURL: https://github.com/akhilkk0803/spring-appCicd
        path: myapp
        targetRevision: HEAD
        helm:
            values: |
                image:
                    repository: akhilkk03/spring-app
                    tag: latest
    syncPolicy:
        automated:
            prune: true
            selfHeal: true



