replicaCount: 2
image:
  repository: akhilkk03/spring-app
  tag: v7
  pullPolicy: IfNotPresent
  

service:
 type: LoadBalancer
 port: 9090
 targetPort: 9090

hpa:
  enabled: false

ingress:
  enabled: false
autoscaling:
  enabled: false
serviceAccount:
  enabled: false


